[build]
  command = "npm install && npm run build"
  publish = "frontend"
  functions = "functions-build"  # Changed from netlify/functions to functions-build

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200