[build]
  command = "pip install -r requirements.txt"
  environment = { PYTHON_VERSION = "3.13" }

[functions]
  directory = "src"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
