[build]
  command = "pip install -r requirements.txt && python build_frontend.py"
  publish = "frontend"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200