[build]
  command = "pip install -r requirements.txt && uvicorn src.orchestrator:app"
  publish = "frontend"
  environment = { PYTHON_VERSION = "3.13" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
